# Generated by Django 3.2.3 on 2021-07-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Economic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('create_date', models.CharField(max_length=100)),
                ('vote', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
        ),
    ]
