# Generated by Django 3.2.3 on 2021-07-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economic',
            name='vote',
        ),
    ]
